name: Benchmark Suite

on:
  label:
    types: [created]

env:
  VERBOSE: true
  ENVIRONMENT_UPSTREAM: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1481114
          access_token: ${{ secrets.GITHUB_TOKEN }}


  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make bench"
