name: code

on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - ".github/workflows/code.yml"
      - "lib/*s"
      - "proto/**"
      - "scripts/**"
      - "src/**"
      - "tests/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "docker-compose.yml"
      - "rust-toolchain"

env:
  AWS_ACCESS_KEY_ID: fake-aws-key
  AWS_SECRET_ACCESS_KEY: fake-aws-key
  RUST_BACKTRACE: full
  TARGET: x86_64-unknown-linux-gnu
  TEST_LOG: debug
  USE_CONTAINER: none

jobs:
  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          USE_CONTAINER: none
          RUSTFLAGS: "-D warnings"
        run: cargo check --no-default-features --features default-msvc

  test-behavior:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-behavior

  test-shutdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test-shutdown

  test-integration-kubernetes:
    # This is an experimental test. Allow it to fail without failing the whole
    # workflow, but keep it executing on every build to gather stats.
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - v1.18.2
          - v1.17.5
          - v1.16.9
          - v1.15.11
          - v1.14.10
      fail-fast: false
    steps:
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: 'v1.9.2'
          kubernetes version: '${{ matrix.kubernetes }}'
          github token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout
        uses: actions/checkout@v1
      - run: make slim-builds
      - run: make test-integration-kubernetes
        env:
          USE_MINIKUBE_DOCKER: "true"
          CONTAINER_IMAGE_REPO: vector-test
          PACKAGE_DEB_USE_CONTAINER: docker
