name: Experimental Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - master

environment:
  VERBOSE: true

jobs:
  environment-prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make environment-prepare
    - run: docker tag docker.pkg.github.com/timberio/vector/environment docker.pkg.github.com/timberio/vector/environment:$(git rev-parse --verify HEAD)
    - run: docker push docker.pkg.github.com/timberio/vector/environment:$(git rev-parse --verify HEAD)
    - run: docker push docker.pkg.github.com/timberio/vector/environment:latest
  