name: Experimental Suite

on:
  push:
    branches:
      - master
  # TODO: We should never do the docker push on a PR.
  pull_request:
    branches:
        - master

env:
  VERBOSE: true

jobs:
  environment-prepare:
    runs-on: ubuntu-latest
    steps:
    - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - run: make environment-prepare
    - run: docker tag docker.pkg.github.com/timberio/vector/environment docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
    - run: docker push docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
    - run: docker push docker.pkg.github.com/timberio/vector/environment:latest
  
  test:
    needs: environment-prepare
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: /vector
    - run: make test

  bench:
    needs: environment-prepare
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: /vector
    - run: make bench