name: Experimental Suite

on:
  push:
    branches:
      - master
  # TODO: We should never do the docker push on a PR.
  pull_request:
    branches:
        - master

env:
  VERBOSE: true

jobs:
  environment-prepare:
    runs-on: ubuntu-latest
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/timberio/vector/environment:latest
      - uses: actions/checkout@v2
      - run: make environment-prepare
      - run: |
          docker tag docker.pkg.github.com/timberio/vector/environment docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
      - run: docker push docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
  
  test:
    needs: environment-prepare
    runs-on: ubuntu-latest
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
      - uses: actions/checkout@v2
      - run: |
          export ENVIRONMENT=true
          export ENVIRONMENT_AUTOBUILD=false
          export ENVIRONMENT_UPSTREAM=docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
          make test

  bench:
    needs: environment-prepare
    runs-on: ubuntu-latest
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
      - uses: actions/checkout@v2
      - run: |
          export ENVIRONMENT=true
          export ENVIRONMENT_AUTOBUILD=false
          export ENVIRONMENT_UPSTREAM=docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
          make bench