name: Experimental Suite

on:
  push:
    branches:
      - master
  # TODO: We should never do the docker push on a PR.
  pull_request:
    branches:
        - master

env:
  VERBOSE: true
  ENVIRONMENT: true
  ENVIRONMENT_AUTOBUILD: false
  ENVIRONMENT_TTY: false
  ENVIRONMENT_UPSTREAM: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

jobs:
  environment:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_AUTOBUILD: true
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: make environment-prepare
      - run: docker tag docker.pkg.github.com/timberio/vector/environment docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
      - run: docker push docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make test"

  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make bench"

  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-fmt"

  check-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-generate"

  test-integration-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-aws"

  test-integration-clickhouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-clickhouse"

  test-integration-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-docker"

  test-integration-elasticsearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-elasticsearch"

  test-integration-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-gcp"

  test-integration-influxdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-influxdb"

  test-integration-kafka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-kafka"

  test-integration-loki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-loki"

  test-integration-pulsar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-pulsar"

  test-integration-splunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-${{ hashFiles('*.nix') }}
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure shell.nix --run "make check-splunk"
