name: Experimental Suite

on:
  push:
    branches:
      - master
  # TODO: We should never do the docker push on a PR.
  pull_request:
    branches:
        - master

env:
  VERBOSE: true

jobs:
  environment-prepare:
    runs-on: ubuntu-latest
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull docker.pkg.github.com/timberio/vector/environment:latest
      - uses: actions/checkout@v2
      - run: make environment-prepare
      - run: |
        docker tag \
          docker.pkg.github.com/timberio/vector/environment \
          docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
      - run: docker push ${{ env.ENVIRONMENT_UPSTREAM }}

  
  test:
    needs: environment-prepare
    runs-on: ubuntu-latest
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ${{ env.ENVIRONMENT_UPSTREAM }}
      - uses: actions/checkout@v2
      - run: |
        make \
          ENVIRONMENT=true \
          ENVIRONMENT_AUTOBUILD=false \
          ENVIRONMENT_UPSTREAM=docker.pkg.github.com/timberio/vector/environment:${{ github.sha }} \
          test

  bench:
    needs: environment-prepare
    runs-on: ubuntu-latest
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ${{ env.ENVIRONMENT_UPSTREAM }}
      - uses: actions/checkout@v2
      - run: |
        make \
          ENVIRONMENT=true \
          ENVIRONMENT_AUTOBUILD=false \
          ENVIRONMENT_UPSTREAM=docker.pkg.github.com/timberio/vector/environment:${{ github.sha }} \
          bench