name: Lint Suite

on:
  push:
    branches:
      - master
  # TODO: We should never do the docker push on a PR.
  pull_request:
    branches:
        - master

env:
  VERBOSE: true
  ENVIRONMENT_UPSTREAM: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1463054
          access_token: ${{ secrets.GITHUB_TOKEN }}

  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-fmt"

  check-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-generate"

  check-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-markdown"

  check-component-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-component-features"

  check-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-blog"

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # v1 on purpose! v2 gives errors since it's shallow.
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-version"

  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-scripts"

  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check"

  check-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check"

  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          USE_CONTAINER: none
          RUSTFLAGS: "-D warnings"
        run: cargo check --no-default-features --features default-msvc

  check-advisories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check advisories
