name: Lint Suite

on:
  push:
    branches:
      - master
  # TODO: We should never do the docker push on a PR.
  pull_request:
    branches:
        - master

env:
  VERBOSE: true
  ENVIRONMENT_UPSTREAM: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-fmt"

  check-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-generate"

  check-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-generate"
  
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-version"

  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-scripts"

  check-code-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-code"
  
  check-code-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make check-code"

  check-advisories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check advisories