name: Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - master


defaults:
  run:
    shell: nix-shell --pure --run "{0}"

env:
  VERBOSE: true
  ENVIRONMENT_UPSTREAM: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=trace

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: "1463240,1463054"
          access_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test"

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test"

  test-windows:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          USE_CONTAINER: none
          RUSTFLAGS: "-D warnings"
        run: cargo test --no-default-features --features default-msvc

  test-behavior:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-behavior"

  test-shutdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-shutdown"


  test-integration-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-aws"

  test-integration-clickhouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-clickhouse"

  test-integration-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-docker"

  test-integration-elasticsearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-elasticsearch"

  test-integration-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-gcp"

  test-integration-influxdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-influxdb"

  test-integration-kafka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-kafka"

  test-integration-loki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-loki"

  test-integration-pulsar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-pulsar"

  test-integration-splunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make slim-builds"
      - run: nix-shell --pure --run "make test-integration-splunk"

  test-integration-kubernetes:
    # This is an experimental test. Allow it to fail without failing the whole
    # workflow, but keep it executing on every build to gather stats.
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - v1.18.2
          - v1.17.5
          - v1.16.9
          - v1.15.11
          - v1.14.10
      fail-fast: false
    steps:
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: 'v1.9.2'
          kubernetes version: '${{ matrix.kubernetes }}'
          github token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout
        uses: actions/checkout@v1
      - run: USE_CONTAINER=none make slim-builds
      - run: make test-integration-kubernetes
        env:
          USE_MINIKUBE_DOCKER: "true"
          CONTAINER_IMAGE_REPO: vector-test
          PACKAGE_DEB_USE_CONTAINER: docker
