name: Test Suite

on:
  push:
    branches:
      - master
  # TODO: We should never do the docker push on a PR.
  pull_request:
    branches:
        - master

env:
  VERBOSE: true
  ENVIRONMENT_UPSTREAM: docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

jobs:
  environment:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_AUTOBUILD: true
    steps:
      - run: docker login https://docker.pkg.github.com -u hoverbear -p ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: make environment-prepare
      - run: docker push docker.pkg.github.com/timberio/vector/environment:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test"

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # Note: `--pure` may have issues on Mac due to `Security`
      - run: nix-shell --run "echo 'Env installing...'"
      - run: nix-shell --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --run "make test"

  bench:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make bench"

  test-integration-aws:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-aws"

  test-integration-clickhouse:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-clickhouse"

  test-integration-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-docker"

  test-integration-elasticsearch:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-elasticsearch"

  test-integration-gcp:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-gcp"

  test-integration-influxdb:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-influxdb"

  test-integration-kafka:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-kafka"

  test-integration-loki:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-loki"

  test-integration-pulsar:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-pulsar"

  test-integration-splunk:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --pure --run "echo 'Env installing...'"
      - run: nix-shell --pure --run "bash scripts/environment/prepare.sh"
      - run: nix-shell --pure --run "make test-integration-splunk"
